---
title: 错误处理
date: 2016-06-28
tags: [Error,JavaScript,DOM]
categories: Dynamic
---

最常用的错误处理机制就是`try-catch`,其中`catch`块需要传入一个参数,接收错误信息,

```javascript
try{
    window.asdfasdf();
} catch(error) {
    console.log(error.message); //window.aasdfasdf is not a function
}
```

`error.message` -- 是所有浏览器都兼容的属性.

使用自定义的`throw`抛出可预料的错误,

```javascript
    function fn(arr) {
        if (!(arr instanceof Array)) {
            throw new Error("fn() : Argument must be an array!");
        }
        return arr.sort();
    }
    fn("sss");  //Uncaught Error: fn() : Argument must be an array!
```

任何没有通过`try-catch`处理的事件都会触发`window`的`onerror`事件,通过自定义这个事件,可以阻止浏览器的默认错误报告行为

```javascript
window.onerror = function(mes, url, line) {
    console.log(mes);
    return true;
}
```

- 上面这段代码就会阻止浏览器的红色文字警告,而变成自定义的控制面板弹出信息,
- 但是虽然没有警告色,但是对于js的阻断效果还是一样的,后面的代码不会被执行.

- 图片的`src`加载之后不是图片格式时候也会抛出错误

```javascript
    var img = new Image();
    img.src = "...";
    wmsj.eventUtil.addHandler(img, "load", function(){
        console.log("img is loaded");
    });
    wmsj.eventUtil.addHandler(img, "error", function(){
        console.log("img error");
    });
```

- 通过使用通用的错误处理函数`assert`,来减少抛出错误的代码量,而且比使用`if-else`更容易读懂.

```javascript
    function assert(condition, message) {
        if (!condition) {
            throw new Error(message);
        }
    }
```


如果是在前面设置了`new Error`类的警告提示，可是在后面的函数中，又想用前面的函数的处理方法，但是不想要它的警告提示，这种时候该怎么办，这就可以使用`try-catch(ex)`,

```javascript
var cookieObj = null,
    try {
        cookieObj = getAll(name);
    } catch (ex) {
        cookieObj = null;
    }
```

正常情况下如果`name`不存在，而使用`getAll(name)`查询时候，就会弹出警告，但是因为使用了`try-catch`结构，所以如果出现异常，就会跳过`try`，直接进入`catch`代码段，把`catch`设置为`null`。